import random
#random.seed(124)
sk1 = random.random()
sk2 = random.uniform (5.0, 10.0)
sk3 = random.randint(1, 5)
sk4 = random.randrange(5.0, 10.0)
izvele = random.choice('ABCDEF')
print("Gadijuma skaitlis=", sk1)
print("Gadijuma skaitlis=", sk2)
print("Gadijuma skaitlis=", sk3)
print("Gadijuma skaitlis=", sk4)
print("Gadijuma skaitlis=", izvele)